config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls', namespace='library')),
    path('users/', include('users.urls', namespace='users')),
]

library/urls.py
from django.urls import path
from .views import BookDeleteView, BookUpdateView, BookCreateView, BooksListView, BookDetailView, AuthorCreateView, \
    AuthorUpdateView, AuthorListView, RecommendBookView, ReviewBookView

# from .views import books_list, book_detail

app_name = 'library'

urlpatterns = [
    path('authors/', AuthorListView.as_view(), name='authors_list'),
    path('author/new/', AuthorCreateView.as_view(), name='author_create'),
    path('author/update/', AuthorUpdateView.as_view(), name='author_update'),

    path('books/', BooksListView.as_view(), name='books_list'),
    path('books/new/', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('books/update/<int:pk>/', BookUpdateView.as_view(), name='book_update'),
    path('books/delete/<int:pk>/', BookDeleteView.as_view(), name='book_delete'),
    path('books/recommend/<int:pk>/', RecommendBookView.as_view(), name='book_recommend'),
    path('books/review/<int:pk>/', ReviewBookView.as_view(), name='book_review'),
]

users/urls.py
from django.urls import path
from .views import RegisterView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='library:books_list'), name='logout'),

]

library/models.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    birth_date = models.DateField(verbose_name='Дата рождения')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'автор'
        verbose_name_plural = 'авторы'
        ordering = ['last_name']


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    publication_date = models.DateField(verbose_name='Дата публикации')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')

    review = models.TextField(null=True, blank=True)
    recommend = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'
        ordering = ['title']
        permissions = [
            ('can_review_book', 'Can review book'),
            ('can_recommend_book', 'Can recommend book'),
        ]


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
    rating = models.ImageField()
    comment = models.TextField()

    def __str__(self):
        return f'Review for {self.book.title}'

library/forms.py
from django import forms
from .models import Author, Book
from django.core.exceptions import ValidationError


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'publication_date', 'author',]

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите название книги'})
        self.fields['publication_date'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите дату публикации'})
        self.fields['author'].widget.attrs.update({'class': 'form-control'})


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'birth_date',]

    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите имя'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите фамилию'})
        self.fields['birth_date'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите дату рождения'})

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if Author.objects.filter(first_name=first_name, last_name=last_name).exists():
            raise ValidationError('Автор с таким именем и фамилией уже существует')
        return cleaned_data

library/views.py
from django.shortcuts import get_object_or_404, redirect
from .models import Author, Book
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import AuthorForm, BookForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseForbidden
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.core.cache import cache
from .services import BookService


class ReviewBookView(LoginRequiredMixin, View):
    def post(self, request, book_id):
        book = get_object_or_404(Book, id=book_id)

        if not request.user.has_perm('Library.can_review_book'):
            return HttpResponseForbidden('У вас нет права для рецензирования книги')

        book.review = request.POST.get('review')
        book.save()

        return redirect('library:book_detail', pk=book_id)


class RecommendBookView(LoginRequiredMixin, View):
    def post(self, request, book_id):
        book = get_object_or_404(Book, id=book_id)

        if not request.user.has_perm('Library.can_recommend_book'):
            return HttpResponseForbidden('У вас нет права для рекомендации книги')

        book.recommend = request.POST.get('review')
        book.save()

        return redirect('library:book_detail', pk=book_id)


class AuthorListView(ListView):
    model = Author
    template_name = 'library/authors_list.html'
    context_object_name = 'authors'

    def get_queryset(self):
        queryset = cache.get('authors_queryset')
        if not queryset:
            queryset = super().get_queryset()
            cache.set('authors_queryset', queryset, 60 * 15)
        return queryset


@method_decorator(cache_page(60 * 15), name='dispatch')
class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'library/author_form.html'
    success_url = reverse_lazy('library:authors_list')


@method_decorator(cache_page(60 * 15), name='dispatch')
class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'library/author_form.html'
    success_url = reverse_lazy('library:authors_list')


@method_decorator(cache_page(60 * 15), name='dispatch')
class BooksListView(LoginRequiredMixin, ListView):
    model = Book
    template_name = 'library/books_list.html'
    context_object_name = 'books'
    # permission_required = 'library.view_book'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(publication_date__year__gt=1800)


class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'publication_date', 'author']
    template_name = 'library/book_form.html'
    success_url = reverse_lazy('library:books_list')
    permission_required = 'library.add_book'


@method_decorator(cache_page(60 * 15), name='dispatch')
class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = 'library/book_detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # print(context)
        context['author_books_count'] = Book.objects.filter(author=self.object.author).count()
        # print(context)
        book_id = self.object.id
        context['average_rating'] = BookService.calculate_average_rating(book_id)
        context['is_popular'] = BookService.is_popular(book_id)

        return context


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    form_class = BookForm
    # fields = ['title', 'publication_date', 'author']
    template_name = 'library/book_form.html'
    success_url = reverse_lazy('library:books_list')
    permission_required = 'library.change_book'


class BookDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Book
    template_name = 'library/book_confirm_delete.html'
    success_url = reverse_lazy('library:books_list')
    permission_required = 'library.delete_book'


# def books_list(request):
#     books = Book.objects.all()
#     context = {'books': books}
#     return render(request, 'library/books_list.html', context)
#
# def book_detail(request, book_id):
#     book = Book.objects.get(id=book_id)
#     context = {'book': book}
#     return render(request, 'library/book_detail.html', context)

library/templates/library/author_form.html
{% extends 'library/base.html' %}

{% block title %}Форма для автора{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Форма для автора</h2>
<form method="post">
     {% csrf_token %}
     {{ form.non_field_errors }}
     {{ form.as_p }}
     <button type="submit" class="btn btn-primary">Сохранить</button>
     <a href="{% url 'library:authors_list' %}" class="btn btn-primary">Отменить</a>
</form>
{% endblock %}

library/templates/library/authors_list.html
{% extends 'library/base.html' %}

{% block title %}Список авторов{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Список авторов</h2>
        <ul class="list-group">
            {% for author in authors %}
            <li class="list-group-item">
              {{ author.first_name }} {{ author.last_name }}

            </li>
            {% endfor %}
        </ul>
{% endblock %}

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Управление библиотекой{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Библиотека</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-lable="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'library:books_list' %}">Главная</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'library:authors_list' %}">Авторы</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'library:books_list' %}">Книги</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'library:author_create' %}">Добавить автора</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'library:book_create' %}">Добавить книгу</a>
                </li>
                {% if user.is_authenticated %}
                 <li class="nav-item active">
                     <form method="post" action="{% url 'users:logout' %}" style="display: inline">
                         {% csrf_token %}
                         <button type="submit" class="btn btn-link nav-link">Выйти</button>
                     </form>
                 </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

library/templates/library/book_confirm_delete.html
{% extends 'library/base.html' %}

{% block title %}Удаление книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Удаление книги</h2>
<p>Вы действительно хотите удалить "{{ book.title }}"</p>
<form  method="post">
     {% csrf_token %}

     <button type="submit" class="btn btn-danger">Подтвердить</button>
     <a href="{% url 'library:books_list' %}" class="btn btn-primary">Отменить</a>
</form>


{% endblock %}

library/templates/library/book_detail.html
{% extends 'library/base.html' %}

{% block title %}Детали книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>{{ book.title }}</h2>
     <p>Автор: {{ book.author.first_name }} {{ book.author.last_name }}</p>
     <p>Дата публикации: {{ book.publication_date|date:"d M Y" }}</p>
     <p>Количество книг автора: {{ author_books_count }}</p>
     <p>Средний рейтинг: {{ average_rating }}</p>
     <p>Популярная: {{ is_popular|yesno:"Да,Нет" }}</p>
<a href="{% url 'library:book_update' book.pk %}" class="btn btn-secondary">Редактировать</a>
<a href="{% url 'library:book_delete' book.pk %}" class="btn btn-danger">Удалить</a>
<a href="{% url 'library:books_list' %}" class="btn btn-primary">Вернуться к списку</a>

{% if 'library.can_review_book' in perms %}
<form action="{% url 'library:book_review' book.id %}" method="post">
     {% csrf_token %}
     <textarea name="review"></textarea>
     <button type="submit">Рецензировать</button>
</form>
{% endif %}

{% if 'library.can_recommend_book' in perms %}
<form action="{% url 'library:book_recommend' book.id %}" method="post">
     {% csrf_token %}
     <textarea name="review"></textarea>
     <button type="submit">Рекомендовать</button>
</form>
{% endif %}

{% endblock %}

library/templates/library/book_form.html
{% extends 'library/base.html' %}

{% block title %}Форма для книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Форма для книги</h2>
<form method="post">
     {% csrf_token %}
     {{ form.non_field_errors }}
     {{ form.as_p }}
     <button type="submit" class="btn btn-primary">Сохранить</button>
     <a href="{% url 'library:books_list' %}" class="btn btn-primary">Отменить</a>
</form>
{% endblock %}

library/templates/library/books_list.html
{% extends 'library/base.html' %}

{% block title %}Список книг{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Список книг</h2>
        <ul class="list-group">
            {% for book in books %}
            <li class="list-group-item">
                <a href="{% url 'library:book_detail' book.pk %}">{{ book.title }}</a> - {{ book.publication_date|date:"d M Y"}} - {{ book.author.first_name }} {{ book.author.last_name }}

            </li>
            {% endfor %}
        </ul>
{% endblock %}

library/templates/library/header.html
<header>
    <h1>Библиотека</h1>
    {% if user.is_authenticated %}
        <p>Добро пожаловать, {{ user.first_name }}!</p>
    {% else %}
        <p>Добро пожаловать на сайт</p>

    {% endif %}
</header>